apiVersion: v1
kind: Service
metadata:
  name: java-ci-cd-svc
  namespace: java-app
spec:
  type: LoadBalancer
  selector:
    app: java-ci-cd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
